// labTests.ts
export const labTests = [
  { id: 1, name: "Complete Blood Count (CBC)" },
  { id: 2, name: "Hemoglobin" },
  { id: 3, name: "Hematocrit" },
  { id: 4, name: "Red Blood Cell Count (RBC)" },
  { id: 5, name: "White Blood Cell Count (WBC)" },
  { id: 6, name: "WBC Differential Count" },
  { id: 7, name: "Platelet Count" },
  { id: 8, name: "Erythrocyte Sedimentation Rate (ESR)" },
  { id: 9, name: "Reticulocyte Count" },
  { id: 10, name: "Prothrombin Time (PT)" },
  { id: 11, name: "Activated Partial Thromboplastin Time (aPTT)" },
  { id: 12, name: "International Normalized Ratio (INR)" },
  { id: 13, name: "Bleeding Time" },
  { id: 14, name: "Clotting Time" },
  { id: 15, name: "Blood Glucose (Fasting)" },
  { id: 16, name: "Blood Glucose (Random)" },
  { id: 17, name: "Oral Glucose Tolerance Test (OGTT)" },
  { id: 18, name: "Glycated Hemoglobin (HbA1c)" },
  { id: 19, name: "Blood Urea Nitrogen (BUN)" },
  { id: 20, name: "Creatinine" },
  { id: 21, name: "Uric Acid" },
  { id: 22, name: "Sodium" },
  { id: 23, name: "Potassium" },
  { id: 24, name: "Chloride" },
  { id: 25, name: "Bicarbonate" },
  { id: 26, name: "Calcium" },
  { id: 27, name: "Magnesium" },
  { id: 28, name: "Phosphate" },
  { id: 29, name: "Total Protein" },
  { id: 30, name: "Albumin" },
  { id: 31, name: "Globulin" },
  { id: 32, name: "Alanine Aminotransferase (ALT)" },
  { id: 33, name: "Aspartate Aminotransferase (AST)" },
  { id: 34, name: "Alkaline Phosphatase (ALP)" },
  { id: 35, name: "Gamma-Glutamyl Transferase (GGT)" },
  { id: 36, name: "Total Bilirubin" },
  { id: 37, name: "Direct Bilirubin" },
  { id: 38, name: "Indirect Bilirubin" },
  { id: 39, name: "Cholesterol (Total)" },
  { id: 40, name: "High-Density Lipoprotein (HDL)" },
  { id: 41, name: "Low-Density Lipoprotein (LDL)" },
  { id: 42, name: "Triglycerides" },
  { id: 43, name: "Troponin" },
  { id: 44, name: "Creatine Kinase-MB (CK-MB)" },
  { id: 45, name: "Lactate Dehydrogenase (LDH)" },
  { id: 46, name: "Amylase" },
  { id: 47, name: "Lipase" },
  { id: 48, name: "Blood Culture" },
  { id: 49, name: "Urine Culture" },
  { id: 50, name: "Stool Culture" },
  { id: 51, name: "Sputum Culture" },
  { id: 52, name: "Wound Swab Culture" },
  { id: 53, name: "Sensitivity Testing (Antibiotic Susceptibility)" },
  { id: 54, name: "Gram Stain" },
  { id: 55, name: "Acid-Fast Bacilli (AFB) Test" },
  { id: 56, name: "Tuberculosis GeneXpert" },
  { id: 57, name: "Viral PCR Test" },
  { id: 58, name: "HIV Test" },
  { id: 59, name: "Hepatitis B Surface Antigen (HBsAg)" },
  { id: 60, name: "Hepatitis C Virus Antibody (HCV)" },
  { id: 61, name: "COVID-19 PCR Test" },
  { id: 62, name: "COVID-19 Antibody Test" },
  { id: 63, name: "Rheumatoid Factor (RF)" },
  { id: 64, name: "C-Reactive Protein (CRP)" },
  { id: 65, name: "Antinuclear Antibody (ANA)" },
  { id: 66, name: "Anti-dsDNA" },
  { id: 67, name: "Complement Levels (C3, C4)" },
  { id: 68, name: "Immunoglobulins (IgG, IgA, IgM, IgE)" },
  { id: 69, name: "Allergy Test (IgE Specific)" },
  { id: 70, name: "PCR (General)" },
  { id: 71, name: "DNA Testing" },
  { id: 72, name: "RNA Testing" },
  { id: 73, name: "Sickle Cell Genotype Test" },
  { id: 74, name: "Urinalysis (Routine Examination)" },
  { id: 75, name: "Urine Microscopy" },
  { id: 76, name: "Urine Protein" },
  { id: 77, name: "Urine Glucose" },
  { id: 78, name: "Urine Ketones" },
  { id: 79, name: "Urine Nitrites" },
  { id: 80, name: "Urine Leukocytes" },
  { id: 81, name: "Urine pH" },
  { id: 82, name: "Urine Specific Gravity" },
  { id: 83, name: "Urine Culture and Sensitivity" },
  { id: 84, name: "Stool Microscopy" },
  { id: 85, name: "Stool Occult Blood Test" },
  { id: 86, name: "Stool Ova and Parasites" },
  { id: 87, name: "Semen Analysis" },
  { id: 88, name: "Biopsy (Histopathology)" },
  { id: 89, name: "Surgical Pathology Examination" },
  { id: 90, name: "Pap Smear" },
  { id: 91, name: "Fine Needle Aspiration Cytology (FNAC)" },
  { id: 92, name: "Frozen Section Analysis" },
  { id: 93, name: "Thyroid Stimulating Hormone (TSH)" },
  { id: 94, name: "Triiodothyronine (T3)" },
  { id: 95, name: "Thyroxine (T4)" },
  { id: 96, name: "Free T3" },
  { id: 97, name: "Free T4" },
  { id: 98, name: "Insulin Level" },
  { id: 99, name: "C-Peptide" },
  { id: 100, name: "Cortisol" },
  { id: 101, name: "Adrenocorticotropic Hormone (ACTH)" },
  { id: 102, name: "Estrogen" },
  { id: 103, name: "Progesterone" },
  { id: 104, name: "Testosterone" },
  { id: 105, name: "Luteinizing Hormone (LH)" },
  { id: 106, name: "Follicle Stimulating Hormone (FSH)" },
  { id: 107, name: "Prolactin" },
  { id: 108, name: "Beta Human Chorionic Gonadotropin (β-hCG)" },
  { id: 109, name: "Vitamin D" },
  { id: 110, name: "Vitamin B12" },
  { id: 111, name: "Folate" },
  { id: 112, name: "Drug Screening Test" },
  { id: 113, name: "Toxicology Screen" },
  { id: 114, name: "Blood Alcohol Level" },
  { id: 115, name: "Heavy Metal Screen (Lead, Mercury)" },
  { id: 116, name: "Carboxyhemoglobin" },
  { id: 117, name: "Methemoglobin" },
  { id: 118, name: "Blood Group (ABO)" },
  { id: 119, name: "Rhesus Factor (Rh)" },
  { id: 120, name: "Crossmatching Test" },
  { id: 121, name: "Direct Coombs Test" },
  { id: 122, name: "Indirect Coombs Test" },
  { id: 123, name: "Malaria Parasite Test (MP)" },
  { id: 124, name: "Thick and Thin Blood Film for Malaria" },
  { id: 125, name: "Rapid Diagnostic Test (RDT) for Malaria" },
  { id: 126, name: "Stool Antigen Test" },
  { id: 127, name: "Helicobacter pylori Test" },
  { id: 128, name: "Tumor Markers (PSA, CA-125, CA 19-9, AFP, CEA)" },
  { id: 129, name: "D-Dimer" },
  { id: 130, name: "Ferritin" },
  { id: 131, name: "Iron" },
  { id: 132, name: "Total Iron Binding Capacity (TIBC)" },
  { id: 133, name: "Transferrin" },
  { id: 134, name: "Osmolality (Serum)" },
  { id: 135, name: "Osmolality (Urine)" },
  { id: 136, name: "Lactate" },
  { id: 137, name: "Procalcitonin" },
  { id: 138, name: "Beta-2 Microglobulin" },
  { id: 139, name: "Homocysteine" },
  { id: 140, name: "Creatinine Clearance Test" },
  { id: 141, name: "Microalbuminuria Test" },
  { id: 142, name: "Sweat Chloride Test" },
  { id: 143, name: "Arterial Blood Gas (ABG)" },
  { id: 144, name: "Venous Blood Gas (VBG)" },
  { id: 145, name: "Coagulation Factor Assays" },
  { id: 146, name: "Platelet Function Test" },
  { id: 147, name: "Thrombophilia Screening" },
  { id: 148, name: "Autoimmune Panel" },
  { id: 149, name: "Fertility Hormone Panel" },
  { id: 150, name: "Prenatal Screening Tests" },
];