export const xrayTests = [
  { id: 1, name: "Chest X-Ray PA View" },
  { id: 2, name: "Chest X-Ray AP View" },
  { id: 3, name: "Chest X-Ray Lateral View" },
  { id: 4, name: "Chest X-Ray Oblique View" },
  { id: 5, name: "Chest X-Ray Decubitus View" },
  { id: 6, name: "Chest X-Ray Lordotic View" },
  { id: 7, name: "Rib X-Ray" },
  { id: 8, name: "Sternum X-Ray" },
  { id: 9, name: "Clavicle X-Ray" },
  { id: 10, name: "Scapula X-Ray" },
  { id: 11, name: "Shoulder X-Ray AP View" },
  { id: 12, name: "Shoulder X-Ray Lateral View" },
  { id: 13, name: "Shoulder X-Ray Axillary View" },
  { id: 14, name: "Humerus X-Ray" },
  { id: 15, name: "Elbow X-Ray AP View" },
  { id: 16, name: "Elbow X-Ray Lateral View" },
  { id: 17, name: "Forearm X-Ray" },
  { id: 18, name: "Wrist X-Ray PA View" },
  { id: 19, name: "Wrist X-Ray Lateral View" },
  { id: 20, name: "Wrist X-Ray Oblique View" },
  { id: 21, name: "Hand X-Ray PA View" },
  { id: 22, name: "Hand X-Ray Oblique View" },
  { id: 23, name: "Finger X-Ray" },
  { id: 24, name: "Thumb X-Ray" },
  { id: 25, name: "Cervical Spine X-Ray AP View" },
  { id: 26, name: "Cervical Spine X-Ray Lateral View" },
  { id: 27, name: "Cervical Spine X-Ray Oblique View" },
  { id: 28, name: "Cervical Spine X-Ray Open Mouth View" },
  { id: 29, name: "Thoracic Spine X-Ray AP View" },
  { id: 30, name: "Thoracic Spine X-Ray Lateral View" },
  { id: 31, name: "Lumbar Spine X-Ray AP View" },
  { id: 32, name: "Lumbar Spine X-Ray Lateral View" },
  { id: 33, name: "Lumbar Spine X-Ray Oblique View" },
  { id: 34, name: "Lumbosacral Spine X-Ray" },
  { id: 35, name: "Sacrum X-Ray" },
  { id: 36, name: "Coccyx X-Ray" },
  { id: 37, name: "Pelvis X-Ray AP View" },
  { id: 38, name: "Pelvis X-Ray Inlet View" },
  { id: 39, name: "Pelvis X-Ray Outlet View" },
  { id: 40, name: "Hip X-Ray AP View" },
  { id: 41, name: "Hip X-Ray Frog Leg View" },
  { id: 42, name: "Femur X-Ray" },
  { id: 43, name: "Knee X-Ray AP View" },
  { id: 44, name: "Knee X-Ray Lateral View" },
  { id: 45, name: "Knee X-Ray Skyline View" },
  { id: 46, name: "Patella X-Ray" },
  { id: 47, name: "Tibia and Fibula X-Ray" },
  { id: 48, name: "Ankle X-Ray AP View" },
  { id: 49, name: "Ankle X-Ray Lateral View" },
  { id: 50, name: "Ankle X-Ray Mortise View" },
  { id: 51, name: "Foot X-Ray AP View" },
  { id: 52, name: "Foot X-Ray Oblique View" },
  { id: 53, name: "Foot X-Ray Lateral View" },
  { id: 54, name: "Toe X-Ray" },
  { id: 55, name: "Calcaneus X-Ray" },
  { id: 56, name: "Heel X-Ray" },
  { id: 57, name: "Skull X-Ray AP View" },
  { id: 58, name: "Skull X-Ray Lateral View" },
  { id: 59, name: "Skull X-Ray Towne’s View" },
  { id: 60, name: "Skull X-Ray Caldwell View" },
  { id: 61, name: "Facial Bones X-Ray" },
  { id: 62, name: "Nasal Bones X-Ray" },
  { id: 63, name: "Orbit X-Ray" },
  { id: 64, name: "Paranasal Sinuses X-Ray Waters View" },
  { id: 65, name: "Paranasal Sinuses X-Ray Caldwell View" },
  { id: 66, name: "Mandible X-Ray" },
  { id: 67, name: "Temporomandibular Joint X-Ray" },
  { id: 68, name: "Dental Bitewing X-Ray" },
  { id: 69, name: "Dental Periapical X-Ray" },
  { id: 70, name: "Dental Panoramic X-Ray (OPG)" },
  { id: 71, name: "Abdomen X-Ray Supine View" },
  { id: 72, name: "Abdomen X-Ray Erect View" },
  { id: 73, name: "Abdomen X-Ray Decubitus View" },
  { id: 74, name: "KUB X-Ray (Kidney Ureter Bladder)" },
  { id: 75, name: "Intravenous Pyelogram (IVP)" },
  { id: 76, name: "Hysterosalpingography (HSG)" },
  { id: 77, name: "Barium Swallow X-Ray" },
  { id: 78, name: "Barium Meal X-Ray" },
  { id: 79, name: "Barium Follow Through X-Ray" },
  { id: 80, name: "Barium Enema X-Ray" },
  { id: 81, name: "Fluoroscopy Upper GI Study" },
  { id: 82, name: "Fluoroscopy Lower GI Study" },
  { id: 83, name: "Fluoroscopy Swallow Study" },
  { id: 84, name: "Fluoroscopy Cystography" },
  { id: 85, name: "Fluoroscopy Myelography" },
  { id: 86, name: "Fluoroscopy Arthrography" },
  { id: 87, name: "Mammography Screening" },
  { id: 88, name: "Mammography Diagnostic" },
  { id: 89, name: "Breast Tomosynthesis" },
  { id: 90, name: "Angiography Coronary" },
  { id: 91, name: "Angiography Cerebral" },
  { id: 92, name: "Angiography Peripheral" },
  { id: 93, name: "Venography" },
  { id: 94, name: "Digital Radiography (DR) X-Ray" },
  { id: 95, name: "Computed Radiography (CR) X-Ray" },
  { id: 96, name: "Portable X-Ray" },
  { id: 97, name: "Interventional Radiology Guided X-Ray Procedures" },
];