import type { doctorProfile } from "@/types/doctorProfile";

export const dummyDoctors: doctorProfile[] = [
  {
    personalInfo: {
      id: "SP-1001",
      fullName: "Dr. Sarah Johnson",
      dateOfBirth: "1985-04-12",
      gender: "Female",
      nationality: "Nigerian",
      phone: "+2348012345678",
      email: "sarah.johnson@example.com",
      address: "12 Admiralty Way, Lekki, Lagos",
      idDocument: "Passport - A12345678",
      emergencyContact: "Michael Johnson (+2348098765432)",
      imageUrl: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=600",
      hospital: "City Hospital",
      status: "assigned",
    },
    qualifications: {
      medicalDegree: "MBBS",
      specialization: "Cardiologist",
      licenses: "Medical and Dental Council of Nigeria (MDCN)",
      boardCertifications: "West African College of Physicians",
      additionalCertifications: "ACLS, CPR",
      medicalSchool: "University of Lagos",
      graduationYear: "2009",
    },
    experience: {
      employers: "LUTH (2015–2022)",
      jobTitles: "Senior Registrar",
      responsibilities: "Patient diagnosis, cardiac procedures",
      references: "Dr. Adeyemi – Chief Cardiologist",
      specializedExperience: "Interventional cardiology",
    },
    cme: {
      workshops: "Annual Cardiology Summit 2023",
      research: "Hypertension management (2022)",
      fellowships: "Cardiology Fellowship – UK",
    },
    skills: {
      clinicalSkills: "Diagnostics, treatment planning",
      surgicalExperience: "Minor cardiac procedures",
      equipment: "ECG, MRI",
      leadership: "Team lead",
    },
    health: {
      medicalHistory: "Fit to practice",
      vaccinations: "Hepatitis B, COVID-19",
      screenings: "TB cleared",
    },
    legal: {
      licenseProof: "Verified MDCN License",
      backgroundCheck: "Cleared",
      insurance: "Malpractice insured",
    },
    statement: {
      motivation: "Improve cardiac healthcare",
      careerGoals: "Lead cardiology department",
      hospitalReason: "Advanced cardiac unit",
    },
    documents: {
      cv: "sarah_johnson_cv.pdf",
      photo: "sarah_johnson.jpg",
      contract: "signed_contract.pdf",
      availability: "1 month notice",
    },
  },

  {
    personalInfo: {
      id: "SP-1002",
      fullName: "Dr. Michael Adeyemi",
      dateOfBirth: "1979-09-03",
      gender: "Male",
      nationality: "Nigerian",
      phone: "+2348031112222",
      email: "m.adeyemi@example.com",
      address: "Ikeja, Lagos",
      idDocument: "National ID - 998822",
      emergencyContact: "Grace Adeyemi",
      imageUrl: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=600",
      hospital: "Lagos General Hospital",
      status: "assigned",
    },
    qualifications: {
      medicalDegree: "MBBS",
      specialization: "Neurologist",
      licenses: "MDCN",
      boardCertifications: "West African College of Physicians",
      additionalCertifications: "Stroke Management",
      medicalSchool: "OAU",
      graduationYear: "2005",
    },
    experience: {
      employers: "Lagos General Hospital",
      jobTitles: "Consultant Neurologist",
      responsibilities: "Neurological diagnosis",
      references: "Dr. Bello",
      specializedExperience: "Stroke care",
    },
    cme: {
      workshops: "WHO Neuro Summit",
      research: "Brain injury research",
      fellowships: "Neurology Fellowship – Canada",
    },
    skills: {
      clinicalSkills: "Neurological exams",
      surgicalExperience: "None",
      equipment: "CT Scan",
      leadership: "Dept coordinator",
    },
    health: {
      medicalHistory: "Fit",
      vaccinations: "Full",
      screenings: "Annual",
    },
    legal: {
      licenseProof: "Verified",
      backgroundCheck: "Cleared",
      insurance: "Insured",
    },
    statement: {
      motivation: "Advance neuro care",
      careerGoals: "National neuro program",
      hospitalReason: "Specialist center",
    },
    documents: {
      cv: "adeyemi_cv.pdf",
      photo: "adeyemi.jpg",
      contract: "contract.pdf",
      availability: "Immediate",
    },
  },

  {
    personalInfo: {
      id: "SP-1003",
      fullName: "Dr. Aisha Bello",
      dateOfBirth: "1990-01-22",
      gender: "Female",
      nationality: "Nigerian",
      phone: "+2348093334444",
      email: "aisha.bello@example.com",
      address: "Abuja",
      idDocument: "Passport - B88333",
      emergencyContact: "Hassan Bello",
      imageUrl: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=600",
      hospital: "National Hospital Abuja",
      status: "pending",
    },
    qualifications: {
      medicalDegree: "MBBS",
      specialization: "Pediatrician",
      licenses: "MDCN",
      boardCertifications: "Paediatric Association",
      additionalCertifications: "Neonatal care",
      medicalSchool: "ABU",
      graduationYear: "2014",
    },
    experience: {
      employers: "National Hospital",
      jobTitles: "Pediatric Specialist",
      responsibilities: "Child healthcare",
      references: "Dr. Musa",
      specializedExperience: "Neonatal ICU",
    },
    cme: {
      workshops: "UNICEF Workshop",
      research: "Child nutrition",
      fellowships: "UK Pediatric Fellowship",
    },
    skills: {
      clinicalSkills: "Child diagnostics",
      surgicalExperience: "None",
      equipment: "Incubators",
      leadership: "Unit supervisor",
    },
    health: {
      medicalHistory: "Fit",
      vaccinations: "Complete",
      screenings: "Annual",
    },
    legal: {
      licenseProof: "Verified",
      backgroundCheck: "Cleared",
      insurance: "Insured",
    },
    statement: {
      motivation: "Improve child survival",
      careerGoals: "Lead pediatric unit",
      hospitalReason: "Child health programs",
    },
    documents: {
      cv: "aisha_cv.pdf",
      photo: "aisha.jpg",
      contract: "contract.pdf",
      availability: "2 weeks",
    },
  },

  {
    personalInfo: {
      id: "SP-1004",
      fullName: "Dr. Chinedu Okafor",
      dateOfBirth: "1982-06-18",
      gender: "Male",
      nationality: "Nigerian",
      phone: "+2348075556666",
      email: "okafor@example.com",
      address: "Enugu",
      idDocument: "Driver License",
      emergencyContact: "Ngozi Okafor",
      imageUrl: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=600",
      hospital: "Enugu Specialist Hospital",
      status: "suspended",
    },
    qualifications: {
      medicalDegree: "MBBS",
      specialization: "Orthopedic Surgeon",
      licenses: "MDCN",
      boardCertifications: "Orthopedic Board",
      additionalCertifications: "Trauma surgery",
      medicalSchool: "UNN",
      graduationYear: "2007",
    },
    experience: {
      employers: "Enugu Specialist Hospital",
      jobTitles: "Orthopedic Surgeon",
      responsibilities: "Bone surgeries",
      references: "Dr. Obi",
      specializedExperience: "Joint replacements",
    },
    cme: {
      workshops: "Orthopedic Summit",
      research: "Bone regeneration",
      fellowships: "Germany",
    },
    skills: {
      clinicalSkills: "Orthopedic assessment",
      surgicalExperience: "Major surgeries",
      equipment: "Surgical systems",
      leadership: "Surgery lead",
    },
    health: {
      medicalHistory: "Fit",
      vaccinations: "Complete",
      screenings: "Annual",
    },
    legal: {
      licenseProof: "Verified",
      backgroundCheck: "Cleared",
      insurance: "Insured",
    },
    statement: {
      motivation: "Restore mobility",
      careerGoals: "Orthopedic institute",
      hospitalReason: "Advanced theatre",
    },
    documents: {
      cv: "okafor_cv.pdf",
      photo: "okafor.jpg",
      contract: "contract.pdf",
      availability: "1 month",
    },
  },
];
